fix(tonic): depend on http at least 1.1.0
We use `try_insert`, which was added in v1.1.0:

* https://github.com/hyperium/http/pull/682

```
error[E0599]: no method named `try_insert` found for mutable reference `&mut HeaderMap` in the current scope
  --> tonic/src/transport/channel/service/user_agent.rs:44:14
   |
42 |           if let Ok(Some(user_agent)) = req
   |  _______________________________________-
43 | |             .headers_mut()
44 | |             .try_insert(USER_AGENT, self.user_agent.clone())
   | |_____________-^^^^^^^^^^
   |
help: there is a method `insert` with a similar name
   |
44 -             .try_insert(USER_AGENT, self.user_agent.clone())
44 +             .insert(USER_AGENT, self.user_agent.clone())
   |
```